### ISSUE TITLE
Not able to run the app after npm install on android.

### ISSUE THREAD

**Issue by NishanthKabra** [alexziskind1/courses-rps-conference-app#1]
Hi @alexziskind1 , i cloned this repo, installed dependencies and tried running the app on android device.
Am running on windows and deploying app to android device.
I see that java, android and some other things are not recognized in the ts files.

I am evaluating nativescript vs ionic2 and want to see a live app on my device for doing it.
Can you please look into this issue. I just want to deploy the conference app on my phone and feel the nativeness of it.

![error](https://cloud.githubusercontent.com/assets/5277668/16527716/0e8545f6-3fd6-11e6-9095-993de050b161.png)

**Comment by alexziskind1** [comment]
Hi Nishanth,
Your screenshot shows Typescript warnings and you can ignore them. Your app should run anyway.
If you don't want to see these warnings, you can add the ios.d.ts and android.d.ts typescript definition files to your project. These files are found in the NativeScript repo
Here is the ios.d.ts file link: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ios.d.ts

Alex
