### ISSUE TITLE
Error running on iOS emulator

### ISSUE THREAD

**Issue by slaction** [alexziskind1/courses-rps-conference-app#2]
Just tried running the app on iOS emulator after fresh download, everything seems okay from nativescript side, but when I run ios emulator I get the following error....

Feb  9 01:22:37 MacBook-Pro logd[20141]: Failed to harvest strings for pathless uuid '00000000-0000-0000-0000-000000000000'
Feb  9 01:22:37 MacBook-Pro com.apple.CoreSimulator.SimDevice.27C353ED-13D5-4C0C-9F26-73D88337DB52.launchd_sim[20130] (UIKitApplication:com.nuvious.rpsconf[0xe5d2][20698]): Service exited due to Segmentation fault: 11
file:///app/tns_modules/utils/utils.js:182:72: JS ERROR TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)

The attempts to open but is instantly shut down and then terminal hangs and has to be manually quit.

I also get an error building to Android which I'll post as a separate issue.

**Comment by alexziskind1** [comment]
Hi @slaction . Thanks for the heads up. I've updated this demo to the latest NativeScript version with instructions on running it if you have CLI version 2.5.0 installed (see README).
I've tested on iOS and Android and they both work now.
