### ISSUE TITLE
Error building to Android

### ISSUE THREAD

**Issue by slaction** [alexziskind1/courses-rps-conference-app#3]
I'm using Genymotion as the emulator.  The project builds and the following errors are displayed on the app screen....

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error: java.lang.ClassNotFoundException: com.tns.FragmentClass
    java.lang.Class.classForName(Native Method)
    java.lang.Class.forName(Class.java:309)
    java.lang.Class.forName(Class.java:273)
    com.tns.Runtime.getClassForName(Runtime.java:1107)
    com.tns.ClassResolver.resolveClass(ClassResolver.java:57)
    com.tns.Runtime.resolveClass(Runtime.java:649)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
  

it wouldn't allow me to copy more than that.

**Comment by alexziskind1** [comment]
Hi @slaction . Thanks for the heads up. I've updated this demo to the latest NativeScript version with instructions on running it if you have CLI version 2.5.0 installed (see README).
I've tested on iOS and Android and they both work now.
