### ISSUE TITLE
Error running iOS still

### ISSUE THREAD

**Issue by slaction** [alexziskind1/courses-rps-conference-app#4]
With a fresh clone, using the latest version of NativeScript, running npm install and then tns run ios --emulator I'm getting the following errors on build.

Executing before-watch hook from /Users/mac/Desktop/conference/courses-rps-conference-app/rps-conf/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
1   0x109f2733c -[TNSRuntime executeModule:referredBy:]
2   0x109a933b9 main
3   0x10b08768d start
4   0x1
file:///app/tns_modules/tns-core-modules/utils/utils.js:182:72: JS ERROR TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)
Feb  9 20:30:54 MacBook-Pro com.apple.CoreSimulator.SimDevice.27C353ED-13D5-4C0C-9F26-73D88337DB52.launchd_sim[30307] (UIKitApplication:com.nuvious.rpsconf[0x3554][31156]): Service exited due to Segmentation fault: 11
app/pages/session-page/session-page.ts(54,26): error TS2304: Cannot find name 'android'.

app/pages/session-page/session-page.ts(54,49): error TS2304: Cannot find name 'android'.

app/pages/session-page/session-page.ts(56,25): error TS2304: Cannot find name 'android'.

app/pages/session-page/session-page.ts(57,25): error TS2304: Cannot find name 'android'.
app/pages/session-page/session-page.ts(60,32): error TS2304: Cannot find name 'android'.
app/pages/session-page/session-page.ts(65,30): error TS2304: Cannot find name 'UIActivityViewController'.

app/pages/session-page/session-page.ts(67,11): error TS2304: Cannot find name 'UIViewController'.

app/services/favorites-service.ts(39,30): error TS2304: Cannot find name 'java'.
app/services/favorites-service.ts(39,66): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(42,29): error TS2304: Cannot find name 'android'.

app/services/favorites-service.ts(58,28): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(63,30): error TS2304: Cannot find name 'android'.
app/services/favorites-service.ts(66,35): error TS2304: Cannot find name 'java'.
app/services/favorites-service.ts(67,33): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(70,46): error TS2304: Cannot find name 'android'.
app/services/favorites-service.ts(75,38): error TS2304: Cannot find name 'android'.
app/services/favorites-service.ts(76,44): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(76,67): error TS2304: Cannot find name 'java'.
app/services/favorites-service.ts(77,42): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(78,43): error TS2304: Cannot find name 'java'.

app/services/favorites-service.ts(79,36): error TS2304: Cannot find name 'android'.
app/services/favorites-service.ts(84,25): error TS2304: Cannot find name 'EKEventStore'.
app/services/favorites-service.ts(85,55): error TS2304: Cannot find name 'EKEntityTypeEvent'.
app/services/favorites-service.ts(85,100): error TS2304: Cannot find name 'NSError'.

app/services/favorites-service.ts(90,29): error TS2304: Cannot find name 'EKEvent'.
app/services/favorites-service.ts(92,34): error TS2304: Cannot find name 'NSTimeZone'.

app/services/favorites-service.ts(93,35): error TS2304: Cannot find name 'NSDate'.
app/services/favorites-service.ts(94,33): error TS2304: Cannot find name 'NSDate'.

app/services/favorites-service.ts(97,32): error TS2304: Cannot find name 'EKAlarm'.
app/services/favorites-service.ts(99,26): error TS2304: Cannot find name 'NSError'.

app/services/favorites-service.ts(100,68): error TS2304: Cannot find name 'EKSpan'.
app/services/favorites-service.ts(129,29): error TS2304: Cannot find name 'android'.

app/services/favorites-service.ts(129,72): error TS2304: Cannot find name 'android'.

app/services/favorites-service.ts(132,25): error TS2304: Cannot find name 'EKEventStore'.
app/services/favorites-service.ts(133,55): error TS2304: Cannot find name 'EKEntityTypeEvent'.

app/services/favorites-service.ts(133,100): error TS2304: Cannot find name 'NSError'.
app/services/favorites-service.ts(140,69): error TS2304: Cannot find name 'EKSpan'.

app/shared/navigation.ts(39,59): error TS2304: Cannot find name 'UIColor'.

**Comment by alexziskind1** [comment]
I've done another push to the update_2.5.0 branch. Please try that one. I've also updated README with the steps I use to get everything working.
